"""
Golden-value lock for Table 5 (cross-screen sufficiency-regime summary), generated by
scripts/make_regime_summary_table.py from committed fixtures. Locks the EmeraldBay N>=400 decision and
the six-screen regime numbers so a fixture drift or an accidental threshold change fails CI.
"""
import os, json, subprocess, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FX = os.path.join(ROOT, "fixtures")


def _load(n):
    return json.load(open(os.path.join(FX, n)))


def test_emeraldbay_spectrum_is_N_ge_400():
    """EmeraldBay spectrum must be over the 958 groups with N>=400 (the held-out threshold),
    NOT the fixture's native N>=300 (1,064 groups, a slope-test artifact)."""
    D = [r for r in _load("emeraldbay_falsification_full.json")["per_group_slope"] if r["N"] >= 400]
    assert len(D) == 958
    N = np.array([r["N"] for r in D], float)
    nstar = 2 * np.array([r["pred_slope"] for r in D]) / 0.1 ** 2
    over = 100 * np.mean(nstar < N); ghost = 100 * np.mean(nstar > 50000); under = 100 - over - ghost
    assert round(over, 1) == 4.5
    assert round(under, 1) == 82.9
    assert round(ghost, 1) == 12.6
    assert round(float(np.median([r["m"] for r in D])), 2) == 0.75
    assert int(np.median(N)) == 1078


def test_genetic_n_is_scored_count():
    """Genetic n in Table 5 is the SCORED gene count (>=25 cells), below the targeted 18,903 / 2,393."""
    g = _load("genetic_two_arm.json")
    assert g["orion_HCT116"]["n_perturbations"] == 17585
    assert g["orion_HEK293T"]["n_perturbations"] == 17856
    assert g["trade_jurkat"]["n_perturbations"] == 2187
    assert g["trade_hepg2"]["n_perturbations"] == 1883
    # detectable / over / not-detectable locked (denominator = detectable for over/under)
    assert [g[k]["pct_detectable"] for k in ("orion_HCT116", "orion_HEK293T", "trade_jurkat", "trade_hepg2")] \
        == [14.7, 35.3, 70.6, 60.9]
    assert [g[k]["pct_not_detectable"] for k in ("orion_HCT116", "orion_HEK293T", "trade_jurkat", "trade_hepg2")] \
        == [85.3, 64.7, 29.4, 39.1]


def test_table5_regenerates_identically():
    """The committed fixtures/regime_summary_table.md must match a fresh regeneration."""
    committed = open(os.path.join(FX, "regime_summary_table.md")).read()
    out = subprocess.run([sys.executable, os.path.join(ROOT, "scripts", "make_regime_summary_table.py")],
                         capture_output=True, text=True, cwd=ROOT)
    assert out.returncode == 0, out.stderr
    assert committed.strip() == out.stdout.strip()
    # spot-check two rows are present with the locked denominators
    assert "| EmeraldBay | condition × line | 958 |" in committed
    assert "| Orion HCT116 | gene × line | 17,585 | 14.7 | 85.3 | 0.0 | 100.0 | n/a | detectable |" in committed
