"""
Generate the manuscript figures from committed fixtures. Vector PDF (for the paper) + PNG (preview),
written to figures/. Palette: Okabe-Ito (the field-standard colourblind-safe qualitative set); series also
carry distinct markers/linestyles and direct labels, so identity is never colour-alone.

  Fig 2  geometry schematic (angular error: along- vs across-signal noise; 1/sqrt(n) shrinkage)
  Fig 3  Tahoe-100M n* sufficiency spectrum
  Fig 4  cross-modality summary: magnitude distributions + OVER/UNDER/Ghost across all datasets
         (saved as fig4_crossmodality_summary; the function is still named fig5_crossmodality)
  Fig 5  per-dataset held-out falsification -> generated by scripts/make_heldout_figure.py
  (retired: fig4_emeraldbay + fig6_trade_validation, the old shared-cell-line/showcase figures)

Run:  python scripts/make_manuscript_figures.py
"""
import os, json, numpy as np, pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import LogLocator

FIG = "figures"; FX = "fixtures"; os.makedirs(FIG, exist_ok=True)

# Okabe-Ito
BLUE, VERM, GREEN, ORANGE, PURPLE, SKY, YELLOW, BLACK, GRAY = (
    "#0072B2", "#D55E00", "#009E73", "#E69F00", "#CC79A7", "#56B4E9", "#F0E442", "#111111", "#9A9A9A")
REG = {"OVER": GREEN, "UNDER": ORANGE, "Ghost": VERM}   # ordinal good->bad, always labelled
POOL, NOTDET = "#B8B8B8", "#3A3A3A"                       # neutral greys for the two "no quota" regimes

plt.rcParams.update({
    "figure.dpi": 140, "savefig.dpi": 300, "font.size": 9, "axes.titlesize": 10,
    "axes.labelsize": 9, "legend.fontsize": 8, "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": "#E6E6E6", "grid.linewidth": 0.6, "axes.axisbelow": True,
    "axes.edgecolor": "#444444", "xtick.color": "#444444", "ytick.color": "#444444",
    "text.color": BLACK, "axes.labelcolor": BLACK, "figure.facecolor": "white", "savefig.bbox": "tight",
})

def save(fig, name):
    for ext in ("pdf", "png"):
        fig.savefig(f"{FIG}/{name}.{ext}")
    plt.close(fig); print(f"  wrote {FIG}/{name}.pdf/.png")


def fig2_geometry():
    """Schematic: the sampling error of the estimated effect vector splits into an along-signal part
    (changes the length only) and an across-signal part (rotates the direction). The cloud of
    estimates, and its RMS radius, shrink as 1/sqrt(n); only the across-signal part enters theta."""
    from matplotlib.patches import Circle, Arc, Polygon
    fig, axs = plt.subplots(1, 2, figsize=(7.4, 2.7), gridspec_kw=dict(wspace=0.04))
    v = np.array([3.0, 0.0]); m = np.linalg.norm(v); u = v / m
    ORIGIN = np.zeros(2)
    NOISE = 2.6                                          # per-cell scatter (illustrative units)
    for ax, n, letter in [(axs[0], 12, "a"), (axs[1], 200, "b")]:
        rng = np.random.default_rng(7)
        sd = NOISE / np.sqrt(n)
        est = v + rng.normal(0, sd, size=(60, 2))
        # cloud of possible estimates + its RMS radius
        ax.add_patch(Circle(v, sd, facecolor=SKY, alpha=0.12, edgecolor=SKY, lw=0.9, ls="--", zorder=1))
        ax.scatter(est[:, 0], est[:, 1], s=7, color=SKY, alpha=0.55, edgecolor="none", zorder=2)
        # true effect vector
        ax.annotate("", xy=v, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=2.4, color=BLACK,
                    shrinkA=0, shrinkB=0, mutation_scale=14), zorder=5)
        ax.plot(0, 0, "o", color=BLACK, ms=3.5, zorder=6)
        ax.text(1.15, -0.26, r"$v$  true effect", color=BLACK, fontsize=8, ha="center", va="top")
        if n == 12:
            vh = np.array([3.50, 0.70])                  # one illustrative estimate, at ~1 RMS radius
            e = vh - v; along = (e @ u) * u; perp = e - along
            foot = v + along
            # estimate
            ax.annotate("", xy=vh, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=1.3, color="#7A7A7A",
                        shrinkA=0, shrinkB=0, mutation_scale=12), zorder=4)
            ax.plot(*vh, "o", color=BLACK, ms=4, zorder=7)
            ax.text(vh[0] - 0.12, vh[1] + 0.12, r"$\hat v$  estimate", fontsize=8, ha="right", va="bottom")
            # decomposition of the error e = vh - v
            ax.plot([v[0], foot[0]], [v[1], foot[1]], color=BLUE, lw=2.4, solid_capstyle="round", zorder=6)
            ax.plot([foot[0], vh[0]], [foot[1], vh[1]], color=VERM, lw=2.4, solid_capstyle="round", zorder=6)
            s = 0.13                                     # right-angle marker at the foot
            ax.add_patch(Polygon([foot + (-s, 0), foot + (-s, s), foot + (0, s)], closed=False,
                                 fill=False, edgecolor="#555555", lw=0.8, zorder=6))
            # labels for the two components, placed clear of the cloud
            ax.annotate("along-signal\nchanges length only", xy=(v[0] + along[0] * 0.5, -0.04), xytext=(5.05, -0.7),
                        color=BLUE, fontsize=7.5, ha="center", va="top",
                        arrowprops=dict(arrowstyle="-", color=BLUE, lw=0.7, shrinkB=3), zorder=8)
            ax.annotate("across-signal\nrotates the direction", xy=(foot[0] + 0.04, foot[1] + perp[1] * 0.5),
                        xytext=(4.25, 0.85), color=VERM, fontsize=7.5, ha="left", va="center",
                        arrowprops=dict(arrowstyle="-", color=VERM, lw=0.7, shrinkB=3), zorder=8)
            # angle
            th = np.degrees(np.arctan2(vh[1], vh[0]))
            ax.add_patch(Arc(ORIGIN, 2.4, 2.4, theta1=0, theta2=th, color="#555555", lw=1.0, zorder=5))
            ax.text(1.45, 0.20, r"$\theta$", color="#333333", fontsize=11, ha="center", va="center")
            ax.text(v[0] - 0.95, -sd - 0.12, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="top")
        else:
            ax.text(v[0], sd + 0.16, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="bottom")
            ax.text(v[0] + 0.1, -0.55, r"$\hat v$ locks onto $v$,  $\theta \to 0$", color="#333333",
                    fontsize=8, ha="center", va="top")
        ax.set_title(f"({letter})  {'few' if n == 12 else 'many'} cells per arm,  $n$ = {n}",
                     fontsize=9, loc="left", pad=6)
        ax.set_xlim(-0.3, 6.2); ax.set_ylim(-1.75, 1.6); ax.set_aspect("equal")
        ax.set_xticks([]); ax.set_yticks([]); ax.grid(False); ax.set_facecolor("none")
        for sp in ax.spines.values(): sp.set_visible(False)
    save(fig, "fig2_geometry")


def fig3_tahoe_spectrum():
    """Tahoe-100M sufficiency spectrum. (a) all 56,827 conditions split into the five regimes, so the
    pool-limited majority (n* = inf, absent from any histogram) is visible; (b) the finite quotas of the
    detectable conditions, stacked by regime, with the median acquired depth and the ghost threshold."""
    z = np.load(f"{FX}/unified_spectrum_per_condition.npz")
    ns_all = z["Tahoe-100M_n_star"]; reg = z["Tahoe-100M_regime"]        # -1.0 marks n* = inf
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}["Tahoe-100M"]
    N0 = summ["median_n_t"]; med = summ["median_n_star"]; ghost = 50000
    segs = [("OVER", summ["pct_over"], REG["OVER"], "over-sampled"),
            ("UNDER", summ["pct_under"], REG["UNDER"], "treated-depth-limited"),
            ("GHOST", summ["pct_ghost"], REG["Ghost"], "ghost"),
            ("POOL-LIMITED", summ["pct_pool_limited"], POOL, "control-pool-limited ($n^\\star=\\infty$)"),
            ("NOT-DETECTABLE", summ["not_detectable_pct"], NOTDET, "not detectable")]

    fig, (ax0, ax1) = plt.subplots(2, 1, figsize=(6.4, 4.8), gridspec_kw=dict(height_ratios=[1, 5.2], hspace=0.78))
    # (a) one horizontal stacked bar over ALL conditions
    left = 0.0
    for key, pct, col, lab in segs:
        ax0.barh(0, pct, left=left, color=col, edgecolor="white", linewidth=1.5, height=0.62)
        if pct >= 8:
            ax0.text(left + pct / 2, 0, f"{pct:.1f}%", ha="center", va="center", fontsize=8,
                     color="white" if key in ("POOL-LIMITED", "NOT-DETECTABLE") else BLACK, fontweight="bold")
        left += pct
    ax0.set_xlim(0, 100); ax0.set_ylim(-0.5, 0.5); ax0.set_yticks([]); ax0.grid(False)
    ax0.set_xticks([0, 25, 50, 75, 100]); ax0.set_xlabel("% of all 56,827 conditions", labelpad=2)
    for sp in ("left", "bottom"): ax0.spines[sp].set_visible(False)
    ax0.set_title("(a)  Regime of every condition (pooled shared DMSO vehicle, $\\theta_\\star$ = 0.1 rad)",
                  loc="left", fontsize=9, pad=4)
    handles = [plt.Rectangle((0, 0), 1, 1, color=col) for _, _, col, _ in segs]
    ax0.legend(handles, [lab for _, _, _, lab in segs], loc="upper center", bbox_to_anchor=(0.5, -0.78),
               ncol=3, frameon=False, fontsize=7.4, handlelength=1.2, columnspacing=1.2)

    # (b) finite quotas of the detectable conditions, stacked by regime
    fin = (ns_all > 0) & (reg != "NOT-DETECTABLE")
    bins = np.logspace(np.log10(ns_all[fin].min()), np.log10(ns_all[fin].max()), 60)
    data = [ns_all[fin & (reg == k)] for k in ("OVER", "UNDER", "GHOST")]
    ax1.hist(data, bins=bins, stacked=True, color=[REG["OVER"], REG["UNDER"], REG["Ghost"]],
             edgecolor="white", linewidth=0.3)
    ax1.set_xscale("log"); ax1.set_xlim(bins[0] * 0.8, bins[-1] * 1.4)
    ymax = ax1.get_ylim()[1] * 1.12; ax1.set_ylim(0, ymax)
    ax1.axvline(N0, color=BLACK, lw=1.3, ls="--"); ax1.axvline(ghost, color=BLACK, lw=1.0, ls=":")
    ax1.text(N0 / 1.12, ymax * 0.97, f"median acquired depth\n$N_0$ = {N0:,}", ha="right", va="top", fontsize=7.5)
    ax1.text(ghost * 1.12, ymax * 0.97, "ghost threshold\n$n^\\star$ = 50,000", ha="left", va="top", fontsize=7.5)
    ax1.axvline(med, color="#666666", lw=1.0, ls="-")
    ax1.text(med * 1.12, ymax * 0.80, f"median finite quota\n$n^\\star$ = {med:,.0f}", ha="left", va="center", fontsize=7.5,
             bbox=dict(fc="white", ec="none", alpha=0.85, pad=1.5))
    ax1.set_xlabel("required treated cells per condition, two-arm quota $n^\\star$ (log scale)")
    ax1.set_ylabel("conditions")
    ax1.set_title(f"(b)  Finite quotas of the detectable conditions ({100 * fin.mean():.1f}% of all), by regime",
                  loc="left", fontsize=9, pad=4)
    save(fig, "fig3_tahoe_spectrum")


def fig5_crossmodality():
    """Cross-modality summary. (a) smoothed magnitude densities on a log axis, medians marked on the curves;
    (b) regime split per screen as fractions of all conditions (genetic: ghost and pool-limited folded
    into under, over among detectable rescaled to all)."""
    from scipy.stats import gaussian_kde
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}
    z = np.load(f"{FX}/unified_spectrum_per_condition.npz")
    # (json name, npz key, legend label, colour, linestyle, is_chemical, x-tick label) -- fixed hue order
    sets = [("Tahoe-100M", "Tahoe-100M", "Tahoe-100M", BLUE, "-", True, "Tahoe-\n100M"),
            ("EmeraldBay", "EmeraldBay", "EmeraldBay", SKY, "-", True, "Emerald-\nBay"),
            ("Orion HCT116", "Orion_HCT116", "Orion HCT116", GREEN, "--", False, "Orion\nHCT116"),
            ("Orion HEK293T", "Orion_HEK293T", "Orion HEK293T", ORANGE, "--", False, "Orion\nHEK293T"),
            ("TRADE Jurkat", "TRADE_Jurkat", "TRADE Jurkat", VERM, "-.", False, "TRADE\nJurkat"),
            ("TRADE HepG2", "TRADE_HepG2", "TRADE HepG2", PURPLE, "-.", False, "TRADE\nHepG2")]
    fig, axs = plt.subplots(1, 2, figsize=(9.6, 3.7), gridspec_kw=dict(width_ratios=[1.15, 1], wspace=0.28))

    # (a) magnitude densities (KDE on log10 m), median marked on each curve
    ax = axs[0]
    grid = np.linspace(np.log10(0.03), np.log10(25), 400)
    for jname, zkey, lab, c, ls, is_chem, tick in sets:
        m = z[zkey + "_m_corr"]; m = np.log10(m[m > 0])
        dens = gaussian_kde(m, bw_method=0.12)(grid)
        ax.plot(10 ** grid, dens, color=c, ls=ls, lw=1.7, label=f"{lab}  (median {10 ** np.median(m):.2f})")
        mid = np.median(m)
        ax.plot(10 ** mid, gaussian_kde(m, bw_method=0.12)([mid])[0], marker="o", ms=5, color=c,
                markeredgecolor="white", markeredgewidth=0.8, zorder=5)
    ax.set_xscale("log"); ax.set_xlim(0.03, 25); ax.set_ylim(0, 3.0)
    ax.set_xlabel("bias-corrected effect magnitude $m$ (log scale)"); ax.set_ylabel("density (per log$_{10}$ unit)")
    ax.set_title("(a)  Effect-magnitude distributions (dots mark medians)", loc="left", fontsize=9, pad=4)
    ax.legend(frameon=False, fontsize=7.2, loc="upper right", handlelength=2.2)

    # (b) regime split per screen, as % of all conditions
    ax = axs[1]
    rows = []
    for jname, zkey, lab, c, ls, is_chem, tick in sets:
        s = summ[jname]; notdet = s["not_detectable_pct"]
        if is_chem:
            over = s["pct_over"]; under = s["pct_under"]; gh = s["pct_ghost"]; pl = s["pct_pool_limited"]
        else:
            over = round(s["detectable_pct"] * s["det_pct_over"] / 100.0, 1)   # over among detectable -> % of all
            gh = 0.0; pl = 0.0
            under = round(100.0 - notdet - over, 1)
        rows.append((tick, over, under, gh, pl, notdet))
    ticks = [r[0] for r in rows]
    ov, un, gh, pl, nd = (np.array([r[i] for r in rows]) for i in range(1, 6))
    x = np.arange(len(rows)); kw = dict(edgecolor="white", linewidth=1.5, width=0.7)
    ax.bar(x, ov, color=REG["OVER"], label="over-sampled (resolvable)", **kw)
    ax.bar(x, un, bottom=ov, color=REG["UNDER"], label="treated-depth-limited", **kw)
    ax.bar(x, gh, bottom=ov + un, color=REG["Ghost"], label="ghost ($n^\\star$ > 50,000)", **kw)
    ax.bar(x, pl, bottom=ov + un + gh, color=POOL, label="control-pool-limited ($n^\\star=\\infty$)", **kw)
    ax.bar(x, nd, bottom=ov + un + gh + pl, color=NOTDET, label="not detectable", **kw)
    for i in range(len(rows)):
        ax.text(i, 101.5, f"{ov[i]:.1f}%", ha="center", va="bottom", fontsize=7.2, color=BLACK)
        if nd[i] >= 10:
            ax.text(i, 100 - nd[i] / 2, f"{nd[i]:.0f}%", ha="center", va="center", fontsize=7.2, color="white")
        if pl[i] >= 10:
            ax.text(i, ov[i] + un[i] + gh[i] + pl[i] / 2, f"{pl[i]:.0f}%", ha="center", va="center", fontsize=7.2, color=BLACK)
    ax.text(-0.55, 109, "over-sampled:", ha="left", va="bottom", fontsize=7.2, color=BLACK)
    ax.set_xticks(x); ax.set_xticklabels(ticks, fontsize=7.5); ax.set_xlim(-0.6, len(rows) - 0.4)
    ax.set_ylabel("% of conditions"); ax.set_ylim(0, 116); ax.set_yticks([0, 25, 50, 75, 100]); ax.grid(axis="x", visible=False)
    ax.set_title("(b)  Sufficiency regime per screen ($\\theta_\\star$ = 0.1 rad)", loc="left", fontsize=9, pad=4)
    ax.legend(frameon=False, fontsize=7.0, loc="upper center", bbox_to_anchor=(0.5, -0.22), ncol=3,
              handlelength=1.2, columnspacing=1.0)
    save(fig, "fig4_crossmodality_summary")


if __name__ == "__main__":
    print("Generating manuscript figures from fixtures ->", FIG)
    fig2_geometry()
    fig3_tahoe_spectrum()
    fig5_crossmodality()
    # Figure 5 (per-dataset held-out) is generated by scripts/make_heldout_figure.py.
    # The former fig4_emeraldbay (shared-cell-line showcase) and fig6_trade_validation are retired:
    # the held-out falsification is now shown uniformly across all datasets in fig5_heldout_per_dataset.
    print("done.")
