"""
Generate the manuscript figures from committed fixtures. Vector PDF (for the paper) + PNG (preview),
written to figures/. Palette: Okabe-Ito (the field-standard colourblind-safe qualitative set); series also
carry distinct markers/linestyles and direct labels, so identity is never colour-alone.

  Fig 2  geometry schematic (angular error: along- vs across-signal noise; 1/sqrt(n) shrinkage)
  Fig 3  Tahoe-100M n* sufficiency spectrum
  Fig 4  cross-modality summary: magnitude distributions + OVER/UNDER/Ghost across all datasets
         (saved as fig4_crossmodality_summary; the function is still named fig5_crossmodality)
  Fig 5  per-dataset held-out falsification -> generated by scripts/make_heldout_figure.py
  (retired: fig4_emeraldbay + fig6_trade_validation, the old shared-cell-line/showcase figures)

Run:  python scripts/make_manuscript_figures.py
"""
import os, json, numpy as np, pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import LogLocator

FIG = "figures"; FX = "fixtures"; os.makedirs(FIG, exist_ok=True)

# Okabe-Ito
BLUE, VERM, GREEN, ORANGE, PURPLE, SKY, YELLOW, BLACK, GRAY = (
    "#0072B2", "#D55E00", "#009E73", "#E69F00", "#CC79A7", "#56B4E9", "#F0E442", "#111111", "#9A9A9A")
REG = {"OVER": GREEN, "UNDER": ORANGE, "Ghost": VERM}   # ordinal good->bad, always labelled

plt.rcParams.update({
    "figure.dpi": 140, "savefig.dpi": 300, "font.size": 9, "axes.titlesize": 10,
    "axes.labelsize": 9, "legend.fontsize": 8, "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": "#E6E6E6", "grid.linewidth": 0.6, "axes.axisbelow": True,
    "axes.edgecolor": "#444444", "xtick.color": "#444444", "ytick.color": "#444444",
    "text.color": BLACK, "axes.labelcolor": BLACK, "figure.facecolor": "white", "savefig.bbox": "tight",
})

def save(fig, name):
    for ext in ("pdf", "png"):
        fig.savefig(f"{FIG}/{name}.{ext}")
    plt.close(fig); print(f"  wrote {FIG}/{name}.pdf/.png")


def fig2_geometry():
    """Schematic: the sampling error of the estimated effect vector splits into an along-signal part
    (changes the length only) and an across-signal part (rotates the direction). The cloud of
    estimates, and its RMS radius, shrink as 1/sqrt(n); only the across-signal part enters theta."""
    from matplotlib.patches import Circle, Arc, Polygon
    fig, axs = plt.subplots(1, 2, figsize=(7.4, 2.7), gridspec_kw=dict(wspace=0.04))
    v = np.array([3.0, 0.0]); m = np.linalg.norm(v); u = v / m
    ORIGIN = np.zeros(2)
    NOISE = 2.6                                          # per-cell scatter (illustrative units)
    for ax, n, letter in [(axs[0], 12, "a"), (axs[1], 200, "b")]:
        rng = np.random.default_rng(7)
        sd = NOISE / np.sqrt(n)
        est = v + rng.normal(0, sd, size=(60, 2))
        # cloud of possible estimates + its RMS radius
        ax.add_patch(Circle(v, sd, facecolor=SKY, alpha=0.12, edgecolor=SKY, lw=0.9, ls="--", zorder=1))
        ax.scatter(est[:, 0], est[:, 1], s=7, color=SKY, alpha=0.55, edgecolor="none", zorder=2)
        # true effect vector
        ax.annotate("", xy=v, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=2.4, color=BLACK,
                    shrinkA=0, shrinkB=0, mutation_scale=14), zorder=5)
        ax.plot(0, 0, "o", color=BLACK, ms=3.5, zorder=6)
        ax.text(1.15, -0.26, r"$v$  true effect", color=BLACK, fontsize=8, ha="center", va="top")
        if n == 12:
            vh = np.array([3.50, 0.70])                  # one illustrative estimate, at ~1 RMS radius
            e = vh - v; along = (e @ u) * u; perp = e - along
            foot = v + along
            # estimate
            ax.annotate("", xy=vh, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=1.3, color="#7A7A7A",
                        shrinkA=0, shrinkB=0, mutation_scale=12), zorder=4)
            ax.plot(*vh, "o", color=BLACK, ms=4, zorder=7)
            ax.text(vh[0] - 0.12, vh[1] + 0.12, r"$\hat v$  estimate", fontsize=8, ha="right", va="bottom")
            # decomposition of the error e = vh - v
            ax.plot([v[0], foot[0]], [v[1], foot[1]], color=BLUE, lw=2.4, solid_capstyle="round", zorder=6)
            ax.plot([foot[0], vh[0]], [foot[1], vh[1]], color=VERM, lw=2.4, solid_capstyle="round", zorder=6)
            s = 0.13                                     # right-angle marker at the foot
            ax.add_patch(Polygon([foot + (-s, 0), foot + (-s, s), foot + (0, s)], closed=False,
                                 fill=False, edgecolor="#555555", lw=0.8, zorder=6))
            # labels for the two components, placed clear of the cloud
            ax.annotate("along-signal\nchanges length only", xy=(v[0] + along[0] * 0.5, -0.04), xytext=(5.05, -0.7),
                        color=BLUE, fontsize=7.5, ha="center", va="top",
                        arrowprops=dict(arrowstyle="-", color=BLUE, lw=0.7, shrinkB=3), zorder=8)
            ax.annotate("across-signal\nrotates the direction", xy=(foot[0] + 0.04, foot[1] + perp[1] * 0.5),
                        xytext=(4.25, 0.85), color=VERM, fontsize=7.5, ha="left", va="center",
                        arrowprops=dict(arrowstyle="-", color=VERM, lw=0.7, shrinkB=3), zorder=8)
            # angle
            th = np.degrees(np.arctan2(vh[1], vh[0]))
            ax.add_patch(Arc(ORIGIN, 2.4, 2.4, theta1=0, theta2=th, color="#555555", lw=1.0, zorder=5))
            ax.text(1.45, 0.20, r"$\theta$", color="#333333", fontsize=11, ha="center", va="center")
            ax.text(v[0] - 0.95, -sd - 0.12, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="top")
        else:
            ax.text(v[0], sd + 0.16, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="bottom")
            ax.text(v[0] + 0.1, -0.55, r"$\hat v$ locks onto $v$,  $\theta \to 0$", color="#333333",
                    fontsize=8, ha="center", va="top")
        ax.set_title(f"({letter})  {'few' if n == 12 else 'many'} cells per arm,  $n$ = {n}",
                     fontsize=9, loc="left", pad=6)
        ax.set_xlim(-0.3, 6.2); ax.set_ylim(-1.75, 1.6); ax.set_aspect("equal")
        ax.set_xticks([]); ax.set_yticks([]); ax.grid(False); ax.set_facecolor("none")
        for sp in ax.spines.values(): sp.set_visible(False)
    save(fig, "fig2_geometry")


def fig3_tahoe_spectrum():
    # unified engine: per-condition n* / regime from the npz, aggregate percentages from the json.
    z = np.load(f"{FX}/unified_spectrum_per_condition.npz")
    ns_all = z["Tahoe-100M_n_star"]                                # -1.0 marks infinite/pool-limited
    ns = ns_all[ns_all > 0]                                        # finite required-cell quotas only
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}["Tahoe-100M"]
    over = summ["pct_over"]; under = summ["pct_under"]; gh = summ["pct_ghost"]; notdet = summ["not_detectable_pct"]
    C = summ["C_largepool"]; med = summ["median_n_star"]; N0 = summ["median_n_t"]; ghost = 50000
    cstr = f"{C:,}".replace(",", "{,}")                            # 4,688 -> LaTeX 4{,}688
    fig, ax = plt.subplots(figsize=(6.4, 3.6))
    bins = np.logspace(np.log10(max(ns.min(), 1)), np.log10(ns.max()), 60)
    ax.hist(ns, bins=bins, color=SKY, edgecolor="white", linewidth=0.3)
    ax.set_xscale("log")
    ax.axvline(N0, color=BLACK, lw=1.6, ls="--")
    ax.axvline(ghost, color=VERM, lw=1.6, ls=":")
    ymax = ax.get_ylim()[1]
    ax.text(N0 * 0.92, ymax * 0.92, f"median depth\n$N_0$ = {N0:,}", ha="right", va="top", fontsize=7.5)
    ax.text(ghost * 1.1, ymax * 0.92, "ghost\nthreshold", ha="left", va="top", fontsize=7.5, color=VERM)
    ax.axvspan(ns.min(), N0, color=GREEN, alpha=0.08)
    ax.text(ns.min() * 1.4, ymax * 0.6, f"over-sampled\n{over:.1f}%", color=GREEN, fontsize=8)
    ax.set_xlabel(r"required cells per arm  $n^\star = " + cstr + r"/m^2$   (log scale)")
    ax.set_ylabel("number of (drug $\\times$ dose $\\times$ line) conditions")
    ax.set_title(f"Tahoe-100M sufficiency spectrum: median $n^\\star$ = {med:,.0f}, "
                 f"{over:.1f}% over / {under:.1f}% under / {gh:.1f}% ghost / {notdet:.1f}% not detectable", fontsize=9)
    save(fig, "fig3_tahoe_spectrum")




def fig5_crossmodality():
    # unified engine: per-condition magnitudes from the npz, regime percentages from the json headline.
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}
    z = np.load(f"{FX}/unified_spectrum_per_condition.npz")
    # (json name, npz key, legend label, colour, linestyle, is_chemical, x-tick label)
    sets = [("Tahoe-100M", "Tahoe-100M", "Tahoe (chem)", BLUE, "-", True, "Tahoe"),
            ("EmeraldBay", "EmeraldBay", "EmeraldBay (chem)", SKY, "-", True, "Emerald\nBay"),
            ("Orion HCT116", "Orion_HCT116", "Orion HCT116", GREEN, "--", False, "Orion\nHCT116"),
            ("Orion HEK293T", "Orion_HEK293T", "Orion HEK293T", ORANGE, "--", False, "Orion\nHEK293T"),
            ("TRADE Jurkat", "TRADE_Jurkat", "TRADE Jurkat", VERM, "-.", False, "TRADE\nJurkat"),
            ("TRADE HepG2", "TRADE_HepG2", "TRADE HepG2", PURPLE, "-.", False, "TRADE\nHepG2")]
    fig, axs = plt.subplots(1, 2, figsize=(9.8, 3.8))
    # (a) bias-corrected magnitude distributions
    ax = axs[0]
    bins = np.logspace(np.log10(0.03), np.log10(20), 55)
    for jname, zkey, lab, c, ls, is_chem, tick in sets:
        m = z[zkey + "_m_corr"]; m = m[m > 0]
        h, edg = np.histogram(m, bins=bins, density=True)
        xc = np.sqrt(edg[:-1] * edg[1:])
        ax.plot(xc, h, color=c, ls=ls, lw=1.8, label=f"{lab} (med {np.median(m):.2f})")
        ax.axvline(np.median(m), color=c, lw=0.8, alpha=0.5)
    ax.set_xscale("log"); ax.set_xlabel(r"effect magnitude  $m$  (log scale)")
    ax.set_ylabel("density"); ax.set_title("(a) Magnitude distributions by dataset", fontsize=9)
    ax.legend(frameon=False, fontsize=6.8, loc="upper right")
    # (b) sufficiency-regime stacked bars. Chemical screens: over/under/ghost/pool-limited/not-detectable
    # over ALL conditions. Genetic screens: over/under split among the DETECTABLE fraction (ghost and
    # pool-limited folded into under), with the not-detectable bucket (m below the sampling floor) on top.
    ax = axs[1]
    rows = []
    for jname, zkey, lab, c, ls, is_chem, tick in sets:
        s = summ[jname]; notdet = s["not_detectable_pct"]
        if is_chem:
            over = s["pct_over"]; under = s["pct_under"]; gh = s["pct_ghost"]; pl = s["pct_pool_limited"]
        else:
            over = round(s["detectable_pct"] * s["det_pct_over"] / 100.0, 1)   # over among detectable -> % of all
            gh = 0.0; pl = 0.0
            under = round(100.0 - notdet - over, 1)
        rows.append((tick, over, under, gh, pl, notdet))
    ticks = [r[0] for r in rows]
    ov = np.array([r[1] for r in rows]); un = np.array([r[2] for r in rows])
    gh = np.array([r[3] for r in rows]); pl = np.array([r[4] for r in rows]); nd = np.array([r[5] for r in rows])
    x = np.arange(len(rows))
    ax.bar(x, ov, color=REG["OVER"], label="OVER (resolvable)", edgecolor="white", linewidth=1.2)
    ax.bar(x, un, bottom=ov, color=REG["UNDER"], label="UNDER", edgecolor="white", linewidth=1.2)
    ax.bar(x, gh, bottom=ov + un, color=REG["Ghost"], label=r"Ghost ($n^\star$>50k)", edgecolor="white", linewidth=1.2)
    ax.bar(x, pl, bottom=ov + un + gh, color="#B0B0B0", label=r"Pool-limited ($n^\star=\infty$)", edgecolor="white", linewidth=1.2)
    ax.bar(x, nd, bottom=ov + un + gh + pl, color="#3A3A3A", label="Not detectable (m below floor)", edgecolor="white", linewidth=1.2)
    for i, (o, ndv) in enumerate(zip(ov, nd)):
        ax.text(i, 101.5, f"{o:.1f}% over", ha="center", va="bottom", fontsize=6.8, color=GREEN)
        if ndv > 6:
            ax.text(i, 100 - ndv / 2, f"{ndv:.0f}%", ha="center", va="center", fontsize=7, color="white")
    ax.set_xticks(x); ax.set_xticklabels(ticks, fontsize=7.5)
    ax.set_ylabel("% of perturbations"); ax.set_ylim(0, 108); ax.grid(axis="x", visible=False)
    ax.set_title(r"(b) Sufficiency regime ($\theta_\star$=0.1 rad)", fontsize=9)
    ax.legend(frameon=True, facecolor="white", edgecolor="none", framealpha=0.9,
              fontsize=7, loc="upper left", bbox_to_anchor=(1.01, 1.0))
    fig.suptitle("Among knockdowns with a measurable signal, essentially nothing is over-sampled; most genetic "
                 "knockdowns fall below the detection floor (m indistinguishable from sampling noise)", fontsize=9.5, y=1.02)
    save(fig, "fig4_crossmodality_summary")




if __name__ == "__main__":
    print("Generating manuscript figures from fixtures ->", FIG)
    fig2_geometry()
    fig3_tahoe_spectrum()
    fig5_crossmodality()
    # Figure 5 (per-dataset held-out) is generated by scripts/make_heldout_figure.py.
    # The former fig4_emeraldbay (shared-cell-line showcase) and fig6_trade_validation are retired:
    # the held-out falsification is now shown uniformly across all datasets in fig5_heldout_per_dataset.
    print("done.")
