"""
Generate the manuscript figures from committed fixtures. Vector PDF (for the paper) + PNG (preview),
written to figures/. Palette: Okabe-Ito (the field-standard colourblind-safe qualitative set); series also
carry distinct markers/linestyles and direct labels, so identity is never colour-alone.

  Fig 2  geometry schematic (angular error: along- vs across-signal noise; 1/sqrt(n) shrinkage)
  Fig 3  Tahoe-100M n* sufficiency spectrum
  Fig 4  cross-modality summary: magnitude distributions + OVER/UNDER/Ghost across all datasets
         (saved as fig4_crossmodality_summary; the function is still named fig5_crossmodality)
  Fig 5  per-dataset held-out falsification -> generated by scripts/make_heldout_figure.py
  (retired: fig4_emeraldbay + fig6_trade_validation, the old shared-cell-line/showcase figures)

Run:  python scripts/make_manuscript_figures.py
"""
import os, json, numpy as np, pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import LogLocator

FIG = "figures"; FX = "fixtures"; os.makedirs(FIG, exist_ok=True)

# Okabe-Ito
BLUE, VERM, GREEN, ORANGE, PURPLE, SKY, YELLOW, BLACK, GRAY = (
    "#0072B2", "#D55E00", "#009E73", "#E69F00", "#CC79A7", "#56B4E9", "#F0E442", "#111111", "#9A9A9A")
REG = {"OVER": GREEN, "UNDER": ORANGE, "Ghost": VERM}   # ordinal good->bad, always labelled
POOL, NOTDET = "#BBBBBB", "#333333"                       # neutral greys for the two "no quota" regimes

plt.rcParams.update({
    "figure.dpi": 140, "savefig.dpi": 300, "font.size": 9, "axes.titlesize": 10,
    "axes.labelsize": 9, "legend.fontsize": 8, "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": "#E6E6E6", "grid.linewidth": 0.6, "axes.axisbelow": True,
    "axes.edgecolor": "#444444", "xtick.color": "#444444", "ytick.color": "#444444",
    "text.color": BLACK, "axes.labelcolor": BLACK, "figure.facecolor": "white", "savefig.bbox": "tight",
})

def save(fig, name):
    for ext in ("pdf", "png"):
        fig.savefig(f"{FIG}/{name}.{ext}")
    plt.close(fig); print(f"  wrote {FIG}/{name}.pdf/.png")


def fig2_geometry():
    """Schematic: the sampling error of the estimated effect vector splits into an along-signal part
    (changes the length only) and an across-signal part (rotates the direction). The cloud of
    estimates, and its RMS radius, shrink as 1/sqrt(n); only the across-signal part enters theta."""
    from matplotlib.patches import Circle, Arc, Polygon
    fig, axs = plt.subplots(1, 2, figsize=(7.4, 2.7), gridspec_kw=dict(wspace=0.04))
    v = np.array([3.0, 0.0]); m = np.linalg.norm(v); u = v / m
    ORIGIN = np.zeros(2)
    NOISE = 2.6                                          # per-cell scatter (illustrative units)
    for ax, n, letter in [(axs[0], 12, "a"), (axs[1], 200, "b")]:
        rng = np.random.default_rng(7)
        sd = NOISE / np.sqrt(n)
        est = v + rng.normal(0, sd, size=(60, 2))
        # cloud of possible estimates + its RMS radius
        ax.add_patch(Circle(v, sd, facecolor=SKY, alpha=0.12, edgecolor=SKY, lw=0.9, ls="--", zorder=1))
        ax.scatter(est[:, 0], est[:, 1], s=7, color=SKY, alpha=0.55, edgecolor="none", zorder=2)
        # true effect vector
        ax.annotate("", xy=v, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=2.4, color=BLACK,
                    shrinkA=0, shrinkB=0, mutation_scale=14), zorder=5)
        ax.plot(0, 0, "o", color=BLACK, ms=3.5, zorder=6)
        ax.text(1.15, -0.26, r"$v$  true effect", color=BLACK, fontsize=8, ha="center", va="top")
        if n == 12:
            vh = np.array([3.50, 0.70])                  # one illustrative estimate, at ~1 RMS radius
            e = vh - v; along = (e @ u) * u; perp = e - along
            foot = v + along
            # estimate
            ax.annotate("", xy=vh, xytext=ORIGIN, arrowprops=dict(arrowstyle="-|>", lw=1.3, color="#7A7A7A",
                        shrinkA=0, shrinkB=0, mutation_scale=12), zorder=4)
            ax.plot(*vh, "o", color=BLACK, ms=4, zorder=7)
            ax.text(vh[0] - 0.12, vh[1] + 0.12, r"$\hat v$  estimate", fontsize=8, ha="right", va="bottom")
            # decomposition of the error e = vh - v
            ax.plot([v[0], foot[0]], [v[1], foot[1]], color=BLUE, lw=2.4, solid_capstyle="round", zorder=6)
            ax.plot([foot[0], vh[0]], [foot[1], vh[1]], color=VERM, lw=2.4, solid_capstyle="round", zorder=6)
            s = 0.13                                     # right-angle marker at the foot
            ax.add_patch(Polygon([foot + (-s, 0), foot + (-s, s), foot + (0, s)], closed=False,
                                 fill=False, edgecolor="#555555", lw=0.8, zorder=6))
            # labels for the two components, placed clear of the cloud
            ax.annotate("along-signal\nchanges length only", xy=(v[0] + along[0] * 0.5, -0.04), xytext=(5.05, -0.7),
                        color=BLUE, fontsize=7.5, ha="center", va="top",
                        arrowprops=dict(arrowstyle="-", color=BLUE, lw=0.7, shrinkB=3), zorder=8)
            ax.annotate("across-signal\nrotates the direction", xy=(foot[0] + 0.04, foot[1] + perp[1] * 0.5),
                        xytext=(4.25, 0.85), color=VERM, fontsize=7.5, ha="left", va="center",
                        arrowprops=dict(arrowstyle="-", color=VERM, lw=0.7, shrinkB=3), zorder=8)
            # angle
            th = np.degrees(np.arctan2(vh[1], vh[0]))
            ax.add_patch(Arc(ORIGIN, 2.4, 2.4, theta1=0, theta2=th, color="#555555", lw=1.0, zorder=5))
            ax.text(1.45, 0.20, r"$\theta$", color="#333333", fontsize=11, ha="center", va="center")
            ax.text(v[0] - 0.95, -sd - 0.12, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="top")
        else:
            ax.text(v[0], sd + 0.16, r"RMS scatter $\propto 1/\sqrt{n}$", color="#3A7CA5", fontsize=7.5,
                    ha="center", va="bottom")
            ax.text(v[0] + 0.1, -0.55, r"$\hat v$ locks onto $v$,  $\theta \to 0$", color="#333333",
                    fontsize=8, ha="center", va="top")
        ax.set_title(f"({letter})  {'few' if n == 12 else 'many'} cells per arm,  $n$ = {n}",
                     fontsize=9, loc="left", pad=6)
        ax.set_xlim(-0.3, 6.2); ax.set_ylim(-1.75, 1.6); ax.set_aspect("equal")
        ax.set_xticks([]); ax.set_yticks([]); ax.grid(False); ax.set_facecolor("none")
        for sp in ax.spines.values(): sp.set_visible(False)
    save(fig, "fig2_geometry")


def export_figure_fixtures():
    """Write the small derived data Figures 3 and 4 need (HANDOFF 6.4), so the figures build on any clone
    without the uncommitted per-condition npz. Numbers match docs/SUPPLEMENT.md."""
    from scipy.stats import gaussian_kde
    z = np.load(f"{FX}/unified_spectrum_per_condition.npz")
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}
    # Figure 3: stacked histogram of the finite quotas of the detectable Tahoe conditions
    ns = z["Tahoe-100M_n_star"]; reg = z["Tahoe-100M_regime"]
    fin = (ns > 0) & (reg != "NOT-DETECTABLE")
    edges = np.logspace(np.log10(20), np.log10(2e6), 37)
    t = summ["Tahoe-100M"]
    fig3 = dict(bin_edges=edges.tolist(),
                counts={k: np.histogram(ns[fin & (reg == k)], bins=edges)[0].tolist() for k in ("OVER", "UNDER", "GHOST")},
                N0=int(t["median_n_t"]), median_n_star=int(round(t["median_n_star"])), ghost=50000,
                pct={"OVER": t["pct_over"], "UNDER": t["pct_under"], "GHOST": t["pct_ghost"],
                     "POOL-LIMITED": t["pct_pool_limited"], "NOT-DETECTABLE": t["not_detectable_pct"]},
                n_all=int(t["n_conditions"]), pct_detectable=round(100 * float(fin.mean()), 1),
                pct_beyond_axis=round(100 * float(np.mean(ns[fin] > edges[-1])), 2))
    json.dump(fig3, open(f"{FX}/fig3_hist.json", "w"), indent=1)
    # Figure 4: KDE of log10(m) per screen (scipy default bandwidth, unscaled) + medians
    grid = np.linspace(-1.6, 1.5, 300); screens = []
    for name, zkey, modality in [("Tahoe-100M", "Tahoe-100M", "chemical"), ("EmeraldBay", "EmeraldBay", "chemical"),
                                 ("Orion HCT116", "Orion_HCT116", "genome-wide"), ("Orion HEK293T", "Orion_HEK293T", "genome-wide"),
                                 ("TRADE Jurkat", "TRADE_Jurkat", "essential-gene"), ("TRADE HepG2", "TRADE_HepG2", "essential-gene")]:
        m = z[zkey + "_m_corr"]; lm = np.log10(m[m > 0])
        screens.append(dict(name=name, modality=modality, density=gaussian_kde(lm)(grid).round(6).tolist(),
                            median_m=round(float(10 ** np.median(lm)), 3)))
    json.dump(dict(grid_log10m=grid.round(6).tolist(), screens=screens), open(f"{FX}/fig4_kde.json", "w"), indent=1)
    print(f"  wrote {FX}/fig3_hist.json, {FX}/fig4_kde.json")


def fig3_tahoe_spectrum():
    """Tahoe-100M sufficiency spectrum (HANDOFF 6.2 spec). (a) labelled regime strip over all conditions,
    no axis, no legend; (b) edge-free stacked histogram of the finite quotas of the detectable conditions,
    reference labels in the top margin, x-axis truncated at 2e6."""
    fx = f"{FX}/fig3_hist.json"
    if not os.path.exists(fx):                             # fall back to the (uncommitted) per-condition npz
        export_figure_fixtures()
    F = json.load(open(fx))
    N0 = F["N0"]; med = F["median_n_star"]; ghost = F["ghost"]; pct = F["pct"]
    segs = [("OVER", pct["OVER"], REG["OVER"], "over-sampled"),
            ("UNDER", pct["UNDER"], REG["UNDER"], "treated-depth-limited"),
            ("GHOST", pct["GHOST"], REG["Ghost"], "ghost"),
            ("POOL-LIMITED", pct["POOL-LIMITED"], POOL, r"control-pool-limited ($n^\star=\infty$)"),
            ("NOT-DETECTABLE", pct["NOT-DETECTABLE"], NOTDET, "not detectable")]
    dark = {"NOT-DETECTABLE"}

    fig, (ax0, ax1) = plt.subplots(2, 1, figsize=(6.4, 4.4), gridspec_kw=dict(height_ratios=[1.7, 6], hspace=0.45))
    # ---- (a) labelled strip -------------------------------------------------------------------
    # names alternate between two rows so neighbours never touch; narrow segments get a leader
    rows_y = {"OVER": -1.05, "UNDER": -0.55, "GHOST": -1.05, "POOL-LIMITED": -0.55, "NOT-DETECTABLE": -1.05}
    left = 0.0
    for key, pct, col, name in segs:
        ax0.barh(0, pct, left=left, color=col, edgecolor="white", linewidth=1, height=0.55)
        xc = left + pct / 2
        if pct >= 8:
            ax0.text(xc, 0, f"{pct:.1f}%", ha="center", va="center", fontsize=8, fontweight="bold",
                     color="white" if key in dark else BLACK)
        else:
            ax0.annotate(f"{pct:.1f}%", xy=(xc, 0.28), xytext=(xc, 0.62), ha="center", va="bottom", fontsize=7.5,
                         arrowprops=dict(arrowstyle="-", lw=0.6, color="#777777"))
        ha = "left" if key == "OVER" else ("right" if key == "NOT-DETECTABLE" else "center")
        xt = 0 if key == "OVER" else (100 if key == "NOT-DETECTABLE" else xc)
        if rows_y[key] < -0.6:                            # lower row: connect with a leader
            ax0.annotate(name, xy=(xc, -0.28), xytext=(xt, rows_y[key]), ha=ha, va="top", fontsize=7.5,
                         arrowprops=dict(arrowstyle="-", lw=0.6, color="#777777", relpos=(0.5 if ha == "center" else (0.02 if ha == "left" else 0.98), 1)))
        else:
            ax0.text(xt, rows_y[key], name, ha=ha, va="top", fontsize=7.5)
        left += pct
    ax0.set_xlim(0, 100); ax0.set_ylim(-1.75, 1.25); ax0.axis("off")
    ax0.set_title(f"(a)  All {F['n_all']:,} conditions by regime", loc="left", fontsize=9, pad=6)

    # ---- (b) stacked density of the finite quotas -----------------------------------------------
    edges = np.array(F["bin_edges"]); xmax = edges[-1]; centers = np.sqrt(edges[:-1] * edges[1:]); widths = np.diff(edges)
    bottom = np.zeros(len(centers))
    for k, col in (("OVER", REG["OVER"]), ("UNDER", REG["UNDER"]), ("GHOST", REG["Ghost"])):
        cnt = np.array(F["counts"][k]); ax1.bar(centers, cnt, width=widths, bottom=bottom, color=col, linewidth=0, align="center")
        bottom += cnt
    ax1.set_xscale("log"); ax1.set_xlim(20, xmax); ax1.set_ylim(0, ax1.get_ylim()[1] * 1.03)
    ax1.grid(False, axis="x"); ax1.grid(True, axis="y"); ax1.set_axisbelow(True)
    ax1.tick_params(labelsize=8)
    ax1.axvline(N0, color=BLACK, lw=1.2, ls="--"); ax1.axvline(med, color="#666666", lw=1.0, ls="-")
    ax1.axvline(ghost, color=BLACK, lw=1.0, ls=":")
    lab = dict(xycoords=("data", "axes fraction"), textcoords="offset points", va="bottom", fontsize=7.5)
    ax1.annotate(f"median depth $N_0$ = {N0:,}", xy=(N0, 1.0), xytext=(-3, 3), ha="right", **lab)
    ax1.annotate(f"median $n^\\star$ = {med:,.0f}", xy=(med, 1.0), xytext=(3, 3), ha="left", **lab)
    ax1.annotate(r"ghost $n^\star \geq$ 50,000", xy=(ghost, 1.0), xytext=(3, 3), ha="left", **lab)
    ax1.set_xlabel(r"required treated cells per condition, two-arm quota $n^\star$", fontsize=8.5)
    ax1.set_ylabel("number of conditions", fontsize=8.5)
    ax1.set_title(f"(b)  Finite quotas of the {F['pct_detectable']:.1f}% detectable conditions", loc="left", fontsize=9, pad=14)
    print(f"    fig3: {F['pct_beyond_axis']:.2f}% of finite quotas beyond the truncated axis (2e6)")
    save(fig, "fig3_tahoe_spectrum")


def fig5_crossmodality():
    """Cross-modality summary (author redesign 2026-09-27: explicit keys for both panels).
    (a) ridgeline of log-magnitude densities, one row per screen, colour = modality (a palette disjoint
    from the regime colours so nothing is shared with panel b), medians as ticks, legend in the panel;
    (b) stacked regime bars for all five regimes straight from the engine headline (same numbers as
    Table 1), in-bar percentages, over-sampled % above each bar, and a five-entry key with the meaning
    of every colour. Saved as fig4_crossmodality_summary."""
    from matplotlib.lines import Line2D
    from matplotlib.patches import Patch
    fx = f"{FX}/fig4_kde.json"
    if not os.path.exists(fx):
        export_figure_fixtures()
    K = json.load(open(fx)); grid = np.array(K["grid_log10m"])
    summ = {s["name"]: s for s in json.load(open(f"{FX}/unified_spectrum.json"))["headline"]}
    screens = K["screens"]                                  # figure order, top to bottom
    MOD = {"chemical": ("#0072B2", "chemical, small-molecule (Vevo Mosaic)"),
           "genome-wide": ("#CC79A7", "genome-wide CRISPRi (X-Atlas/Orion)"),
           "essential-gene": ("#56B4E9", "essential-gene CRISPRi (TRADE)")}
    fig, axs = plt.subplots(1, 2, figsize=(8.0, 3.9), gridspec_kw=dict(width_ratios=[1, 1.12], wspace=0.34))

    # ---- (a) ridgeline -----------------------------------------------------------------------------
    ax = axs[0]; H = 0.82; x = 10 ** grid
    for i, sc in enumerate(screens):
        col = MOD[sc["modality"]][0]; y0 = 5 - i
        d = np.array(sc["density"]); d = d / d.max() * H
        ax.fill_between(x, y0, y0 + d, color=col, alpha=0.30, lw=0)
        ax.plot(x, y0 + d, color=col, lw=1.1)
        med = sc["median_m"]
        ax.plot([med, med], [y0, y0 + H], color=BLACK, lw=1.2)
        ax.annotate(f"{med:.2f}", xy=(med, y0 + H), xytext=(3, -1), textcoords="offset points",
                    ha="left", va="top", fontsize=7, color=BLACK)
    ax.set_xscale("log"); ax.set_xlim(0.03, 30); ax.set_ylim(-0.15, 6.15)
    ax.set_xticks([0.1, 1, 10]); ax.set_xticklabels(["0.1", "1", "10"], fontsize=8)
    ax.set_yticks(range(6)); ax.set_yticklabels([sc["name"] for sc in screens][::-1], fontsize=8)
    ax.spines["left"].set_visible(False); ax.tick_params(axis="y", length=0)
    ax.grid(False, axis="y"); ax.grid(True, axis="x", which="major"); ax.set_axisbelow(True)
    for ysep in (3.5, 1.5):
        ax.axhline(ysep, color="#CCCCCC", lw=0.6, zorder=0)
    ax.set_xlabel(r"bias-corrected effect magnitude $m$ (log scale)", fontsize=8.5)
    ax.set_title("(a)  Effect magnitude per screen", loc="left", fontsize=9)
    handles = [Patch(facecolor=c, edgecolor=c, alpha=0.6, label=l) for c, l in MOD.values()]
    handles.append(Line2D([0], [0], color=BLACK, lw=1.2, label="median $m$"))
    ax.legend(handles=handles, loc="upper left", bbox_to_anchor=(-0.02, -0.16), ncol=2, fontsize=6.6,
              frameon=False, handlelength=1.1, handletextpad=0.5, columnspacing=1.2, labelspacing=0.35,
              borderaxespad=0)

    # ---- (b) stacked bars: all five regimes, from the engine headline (= Table 1) ------------------
    ax = axs[1]
    keys = ["pct_over", "pct_under", "pct_ghost", "pct_pool_limited", "not_detectable_pct"]
    R = np.array([[summ[sc["name"]][k] for sc in screens] for k in keys])     # 5 regimes x 6 screens
    cols = [REG["OVER"], REG["UNDER"], REG["Ghost"], POOL, NOTDET]
    x = np.arange(6, dtype=float); W = 0.62
    base = np.vstack([np.zeros(6), np.cumsum(R, axis=0)[:-1]])
    for k in range(5):
        ax.bar(x, R[k], bottom=base[k], color=cols[k], edgecolor="none", width=W, zorder=2)
        for i in range(6):
            if R[k, i] < 7:
                continue
            txt = f"{R[k, i]:.1f}%" if k == 0 else f"{R[k, i]:.0f}%"
            ax.text(x[i], base[k, i] + R[k, i] / 2, txt, ha="center", va="center", fontsize=7,
                    color="white" if k == 4 else BLACK, zorder=3)
    for i in range(6):                                     # headline number above every bar
        ax.text(x[i], 101.5, f"{R[0, i]:.1f}%", ha="center", va="bottom", fontsize=7.2, fontweight="bold",
                color=REG["OVER"])
    ax.text(-0.55, 101.5, "over-\nsampled", ha="right", va="bottom", fontsize=6.5, color=REG["OVER"],
            linespacing=1.0)
    ax.set_xlim(-0.75, 5.55); ax.set_ylim(0, 112)
    ax.set_yticks([0, 25, 50, 75, 100]); ax.tick_params(axis="y", labelsize=8)
    ax.grid(False); ax.grid(True, axis="y"); ax.set_axisbelow(True)
    ax.set_xticks(x); ax.set_xticklabels(["Tahoe-\n100M", "Emerald-\nBay", "Orion\nHCT116", "Orion\nHEK293T",
                                          "TRADE\nJurkat", "TRADE\nHepG2"], fontsize=6.8)
    ax.set_ylabel("% of conditions", fontsize=8.5)
    ax.set_title("(b)  Sufficiency regime per screen", loc="left", fontsize=9)
    # group brackets under the tick labels
    for (a, b, lab) in ((0, 1, "chemical"), (2, 5, "genetic (CRISPRi)")):
        ax.annotate("", xy=(a - 0.3, -0.135), xytext=(b + 0.3, -0.135), xycoords=("data", "axes fraction"),
                    textcoords=("data", "axes fraction"), arrowprops=dict(arrowstyle="-", lw=0.7, color="#888888"))
        ax.text((a + b) / 2, -0.155, lab, transform=ax.get_xaxis_transform(), ha="center", va="top",
                fontsize=7, color="#666666")
    # key: one entry per regime, top-to-bottom in stack order, with the meaning of each colour
    meaning = [("not detectable", "effect below the sampling floor"),
               ("control-pool-limited", r"$n^\star=\infty$: control pool too small"),
               ("ghost", r"$n^\star>50{,}000$ treated cells"),
               ("treated-depth-limited", r"$n^\star$ above the acquired depth"),
               ("over-sampled", r"$n^\star$ within the acquired depth")]
    handles = [Patch(facecolor=cols[k], edgecolor="none", label=f"{n}\n{m}") for k, (n, m) in zip((4, 3, 2, 1, 0), meaning)]
    leg = ax.legend(handles=handles, loc="upper left", bbox_to_anchor=(1.02, 1.0), fontsize=6.6, frameon=False,
                    handlelength=1.1, handleheight=1.9, handletextpad=0.6, labelspacing=0.9, borderaxespad=0)
    for txt in leg.get_texts():
        txt.set_linespacing(1.15)
    save(fig, "fig4_crossmodality_summary")


if __name__ == "__main__":
    print("Generating manuscript figures from fixtures ->", FIG)
    if os.path.exists(f"{FX}/unified_spectrum_per_condition.npz"):
        export_figure_fixtures()                           # refresh the small committed fixtures when the npz is present
    fig2_geometry()
    fig3_tahoe_spectrum()
    fig5_crossmodality()
    # Figure 5 (per-dataset held-out) is generated by scripts/make_heldout_figure.py.
    # The former fig4_emeraldbay (shared-cell-line showcase) and fig6_trade_validation are retired:
    # the held-out falsification is now shown uniformly across all datasets in fig5_heldout_per_dataset.
    print("done.")
